package patches.projects

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.Project
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    params {
        add {
            param("deploy_brother", """
                #!/bin/bash
                sudo service uwsgi stop
                mkdir -p ~/release/%teamcity.build.branch%
                tar -xf ~/upload/%dep.OPT_MS_TestsAndBuilds_Office_BrotherBot_Build.build.counter%.brother.tar.gz -C ~/release/%teamcity.build.branch%
                ln -s ~/.env ~/release/%teamcity.build.branch%/.env
                unlink ~/BrotherBot
                ln -s ~/release/%teamcity.build.branch% ~/BrotherBot
                sudo service uwsgi start
            """.trimIndent())
        }
        add {
            text("dep.OPT_MS_TestsAndBuilds_Office_BrotherBot_Build.build.counter", "false", display = ParameterDisplay.HIDDEN, allowEmpty = false)
        }
    }
}
